name: cloud-run

on:
  push:
    branches:
      - stage-run

env:
  PUB_REPO_NAME: pub-dashboard
  ADV_REPO_NAME: adv-dashboard
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  CLOUD_RUN_REGION: us-central1
  BEFORE_SHA: ${{ github.event.before }}

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # This step is where our service account will be authenticated
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
          service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
          service_account_email: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn format:check
      - run: yarn affected:deploy --base $BEFORE_SHA
