# https://github.com/marketplace/actions/semantic-pull-request?version=v4.5.0

name: 'Semantic PR'

on:
  pull_request:
  merge_group:

jobs:
  main:
    if: ${{ github.event_name == 'pull_request' }} # only run job if workflow initiated by a pull request event
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
