name: 'todo to issue'

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@master'
      - name: 'TODO to Issue'
        uses: alstr/todo-to-issue-action@v4.9.3
        with:
          AUTO_ASSIGN: true
